name: Build CI

on:

  push:

    branches: [ master ]

jobs:

  gradle:

    name: Gradle CI Build

    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v2

      name: Clone repository

    

    - name: Fix Card

      run: |

        cd app/src/main/java/me/singleneuron/base/bridge

        wget https://raw.githubusercontent.com/Kylepoops/QN-Card/master/CardMsgList.kt -O CardMsgList.kt

        ls

    - name: Prepare Java 11

      uses: actions/setup-java@v1

      with:

        java-version: 11

        java-package: jdk+fx

    - name: Cache Gradle packages

      uses: actions/cache@v2

      with:

        path: ~/.gradle/caches

        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}

        restore-keys: ${{ runner.os }}-gradle

    - name: Build project

      run: |

        if ${{ !!github.head_ref }}; then echo "::warning:: Gradle $WARN_ON_PR"; fi

        gradle wrapper

        bash gradlew build

    

    - name: Upload articact

      uses: actions/upload-artifact@v2

      if: ${{ !github.head_ref }}

      with:

        path: app/build/outputs/apk

        name: gradle
